### ISSUE TITLE
ENG - “United Kingdom of Britain” Is Not A Real Thing

### ISSUE THREAD

**Issue by ForTheImperium** [kalterkrieg/Kalterkrieg-bug-reports#194]
HOI4 version: 1.14.7
Kalterkrieg version: 0.1

If the UK were to give up her claim on (Northern) Ireland, Kingdom of Great Britain should be the new name, instead of the “United Kingdom of Great Britain”.

Never in history had there been a “United Kingdom of Great Britain”. A quick Wikipedia search can tell you that in 1707, the Treaty of Union and Acts of Union 1707 merged the Kingdom of England and the Kingdom of Scotland into one single sovereign state with one single crown called the Kingdom of Great Britain, not the United Kingdom. It would be utterly redundant to put the word “United” here because the concept of Great Britain already contained both England and Scotland.

The word was only added in 1800 when she united with the Kingdom of Ireland and became the UNITED Kingdom of Great Britain AND Ireland through the Act of Union 1800. They had an “and” there, so they had literally unite the two titles. The “and” is what makes her “united”; if Greater Britain were a real phrase, they would have just called the new state the Kingdom of Greater Britain.

**Comment by MrCovenant000** [comment]
The person is right @Axolotl3823 but up to you

**Comment by Axolotl3823** [comment]
This will be addressed more in a future rework of the United Kingdom. But the name will be the United Kingdom of Great Britain.  Simply changing the name back to the Kingdom of Great Britain is a very 2dimension look at history. The UK isn't going back to that form as things have changed a lot. There is historical context for using the name "the United Kingdom of Great Britain" because in the text of both the Union with Scotland Act 1706 and Union with England Act 1707 the name United Kingdom of Great Britain is frequently used. The official name that was adopted afterwards was indeed the Kingdom of Great Britain but the precedence for a United Kingdom was also established. Now in the Kalterkrieg timeline the name United Kingdom with its two variations have existed for over 150 years when they will renounce Northern Ireland. So when the question of what the name should be comes up there two considerations. "the Kingdom of Great Britain" and "the United Kingdom of Great Britain". A variation of United Kingdom has been used as stated for over 150 years and also invokes unity which will be important as both Wales and Scotland will be more regionalist than OTL due to the Union of Britain. 

Therefore the name will stay as the United Kingdom of Great Britain.

Sincerely, Axolotl
