### ISSUE TITLE
Lithuania and White Ruthenia- Weird border bug thing

### ISSUE THREAD

**Issue by CrazyWhatzthis** [kalterkrieg/Kalterkrieg-bug-reports#219]
### OS

Windows 10

### HOI4 Version

Bolivar v1.14.7

### Kalterkrieg Version

1.0? idk release version I think

### List any other mods used

The "HOT" key (nuke hotkey mod)

### Were you using Steam?

Yes

### Were you in multiplayer?

No

### Which expansions do you NOT have?

I have them all.

### Steps to reproduce

I was playing as north/kingdom of france, and the third weltkrieg started, but in the middle of the push in the eastern front, white ruthenia declared independence, and eventually, when the eastern front war was over with scripted peace deal, for some reason, lithuania got all the land that ruthenia should have gotten, making a very thin ruthenia and big lithuania-belarus

### Possible Cause

Ruthenian independence before the eastern front war was over

### Screenshots

![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/175259984/609e61dd-5aa8-491e-a72c-11c01893b69b)

### Save File

[FRA_1955_11_06_05.zip](https://github.com/user-attachments/files/16169053/FRA_1955_11_06_05.zip)

### Log Files

[logs.zip](https://github.com/user-attachments/files/16169069/logs.zip)

### Important Files Attached

- [X] I have attached the game/error logs and a save to go with this report. I understand that failure to do so will likely result in automatic closure of this issue if not enough information is included to determine the cause of this issue.

**Comment by Flizzyclone** [comment]
Fixed by making changes in two spots detailed below for interested parties (Axolotl?):

First, line 1077 of 00_peace_scripted_effects:
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/42476312/a1da7fb6-07c8-4977-bca0-b2fab1ea2885)
to
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/42476312/3432ffef-749c-4461-b86d-7f1cc6416daf)
Secondly, lines 283-286 of KRG_RUS_scripted_effects:
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/42476312/b8bd14e5-38c8-4b13-ba66-faf77b94f296)
to
![image](https://github.com/kalterkrieg/Kalterkrieg-bug-reports/assets/42476312/0e02ffa9-736d-4f65-b5fa-066f85d0b634)
